# Generated by Django 5.0.6 on 2024-09-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('overs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowling_type', models.CharField(max_length=50)),
                ('shot', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=10)),
                ('outcome', models.CharField(max_length=10)),
                ('commentary', models.TextField()),
                ('player', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.match')),
            ],
        ),
    ]
